sudo: required
services:
  - docker

before_install:
  - docker build -t jhonnynho/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jhonnynho/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-093164064398"
  bucket_path: "docker-react"
  on:
    branch: main
  acccess_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"